version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    container_name: postgres_middle_python
    image: postgres:13
    restart: always
    expose:
      - '5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env

  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./movies_admin/config/static:/code/static
    command: >
      bash -c "sleep 5
      && python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.20.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./movies_admin/config/static:/code/static
    ports:
      - '80:80'
    depends_on:
      - admin_panel